# Stage 1: Build the application
FROM node:18 as build

WORKDIR /app

COPY package*.json ./

RUN npm install

COPY . .

# Stage 2: Run the application
FROM node:18-alpine

WORKDIR /app

COPY package*.json ./

RUN npm install --only=production

COPY --from=build /app/ .

CMD ["node", "seed.js"]