global:
  scrape_interval: 15s

scrape_configs:
  - job_name: "admin"
    static_configs:
      - targets: ["admin:8002"]

  - job_name: "rabbitmq"
    static_configs:
      - targets: ["rabbitmq:15672"]
