apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: admin-frontend
  name: admin-frontend
spec:
  type: NodePort
  ports:
    - name: "admin-frontend"
      port: 5002
      targetPort: 3002
      nodePort: 31002
  selector:
    io.kompose.service: admin-frontend
