apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.kompose.service: admin-frontend
  name: admin-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: admin-frontend
  template:
    metadata:
      labels:
        io.kompose.network/rabbitmq-microservices-microservices: "true"
        io.kompose.service: admin-frontend
    spec:
      containers:
        - env:
            - name: PORT
              value: "3002"
            # - name: REACT_APP_API_URL # this does not work because the variable already exists in the container
            #   value: http://admin:8002/api
          image: pesekt1/rabbitmq-microservices-admin-frontend
          name: admin-frontend
          ports:
            - containerPort: 3002
              name: admin-frontend
              # hostPort: 3002
              # protocol: TCP
