apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: admin
  name: admin
spec:
  type: NodePort
  ports:
    - name: "admin"
      port: 8002
      targetPort: 8002
      nodePort: 31802
  selector:
    io.kompose.service: admin
# status:
#   loadBalancer: {}
