apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\Program Files\Kompose\kompose.exe convert
    kompose.version: 1.31.2 (a92241f79)
  creationTimestamp: null
  labels:
    io.kompose.service: admin
  name: admin
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: admin
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: C:\Program Files\Kompose\kompose.exe convert
        kompose.version: 1.31.2 (a92241f79)
      creationTimestamp: null
      labels:
        io.kompose.network/rabbitmq-microservices-microservices: "true"
        io.kompose.service: admin
    spec:
      containers:
        - env:
            - name: ADMIN_FRONTEND_PORT
              value: "3002"
            - name: MYSQL_DATABASE_URL
              value: mysql://yt_node:123456@mysql:3306/yt_node_admin
            - name: PORT
              value: "8002"
            - name: RABBIT_MQ_URL
              value: amqp://guest:guest@rabbitmq:5672/
          image: admin
          name: admin
          ports:
            - containerPort: 8002
              hostPort: 8002
              protocol: TCP
          resources: {}
      restartPolicy: Always
status: {}
