apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: C:\Program Files\Kompose\kompose.exe convert
    kompose.version: 1.31.2 (a92241f79)
  creationTimestamp: null
  labels:
    io.kompose.service: admin-frontend
  name: admin-frontend
spec:
  type: NodePort
  selector:
    app: admin-frontend
  ports:
    - protocol: TCP
      port: 3002
      # targetPort: 3002
      nodePort: 31002
  selector:
    io.kompose.service: admin-frontend
# status:
#   loadBalancer: {}
