apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: main-frontend
  name: main-frontend
spec:
  type: NodePort
  ports:
    - name: "main-frontend"
      port: 5001
      targetPort: 3001
      nodePort: 31001
  selector:
    io.kompose.service: main-frontend
