apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: C:\Program Files\Kompose\kompose.exe convert
    kompose.version: 1.31.2 (a92241f79)
  creationTimestamp: null
  labels:
    io.kompose.service: main
  name: main
spec:
  type: loadBalancer
  ports:
    - name: "main"
      port: 8001
      targetPort: 8001
      nodePort: 31003
  selector:
    io.kompose.service: main
# status:
#   loadBalancer: {}
