# Stage 1: Build the application
FROM node:14 as build

WORKDIR /app

COPY package*.json ./

RUN npm install

COPY . .

RUN npm run build

# Stage 2: Serve the application
FROM nginx:1.19.0-alpine as serve

COPY --from=build /app/build /usr/share/nginx/html

# Copy the nginx configuration file because the default settings is for port 80
COPY nginx.conf /etc/nginx/conf.d/default.conf

# Expose port 3001 for the application
EXPOSE 3001

CMD ["nginx", "-g", "daemon off;"]